### ISSUE TITLE
Create Profile Model

### ISSUE THREAD

**Issue by z3ke1r** [C2-Dev/poof-mark#7]
```python
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.TextField(max_length=100, blank=True, 
            default='The more you poof the better you feel')
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to="media/avatars", blank=True,
            default='media/avatars/default.jpg')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Creates a profile when user is created."""
    
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Saves profile info when user is updated."""
                               
    instance.profile.save()
```

**Comment by z3ke1r** [comment]
We will need to add the media root to `settings.py` and add a default image for no pic users.

```python
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
```

**Comment by z3ke1r** [comment]
@cgeorgiades27  Not sure how this will effect the init.db etc. so I will hold off until you move this to in progress. 

Also there are a bunch of Django libs for managing profile pictures if we wanted to go that route instead. Would add some dependencies though.

**Comment by z3ke1r** [comment]
@cgeorgiades27 Not sure how this will effect the init.db etc. so I will hold off until you move this to in progress.

Also there are a bunch of Django libs for managing profile pictures if we wanted to go that route instead. Would add some dependencies though.

**Comment by cgeorgiades27** [comment]
@z3ke1r master is clean, so go ahead and make a branch.  We can merge them and add more to initDB later.
